### ISSUE TITLE
脸框信息结构体跟SDK文档有出入

### ISSUE THREAD

**Issue by HeChenz** [colin-chang/ArcFace.Net#3]
C# 版本：   
    public struct Rect
    {
        public int Top { get; set; }
        public int Bottom { get; set; }
        public int Left { get; set; }
        public int Right { get; set; }
    }
c++ 版本：
   typedef struct __tag_rect
    {
	    MInt32 left;
	    MInt32 top;
	    MInt32 right;
	    MInt32 bottom;
    } MRECT, *PMRECT;

**Comment by colin-chang** [comment]
已修复，谢谢
