### ISSUE TITLE
希望搜索人脸库SearchFaceAsync增加多线程

### ISSUE THREAD

**Issue by wpdrifter** [colin-chang/ArcFace.Net#4]
希望搜索人脸库SearchFaceAsync增加多线程
初始化InitFaceLibraryAsync也真加多线程
希望能更新多线程，谢谢

**Comment by wpdrifter** [comment]
主要是我的人脸库有10万左右，

**Comment by colin-chang** [comment]
4.1.0之后的版本已支持并发人脸检测。ArcFaceOptions. MaxSingleTypeEngineCount为并发数
