### ISSUE TITLE
是否可以考虑使用imageSharp等跨平台库处理图片

### ISSUE THREAD

**Issue by hyfree** [colin-chang/ArcFace.Net#5]
是否可以考虑使用imageSharp等跨平台库处理图片，来取消对libgdiplus的依赖

**Comment by hyfree** [comment]
https://devblogs.microsoft.com/dotnet/net-core-image-processing/

**Comment by kevin100702** [comment]
为啥把问题关了呢？个人觉得使用imageSharp来做跨平台兼容是很有必要的

**Comment by hyfree** [comment]
> 为啥把问题关了呢？个人觉得使用imageSharp来做跨平台兼容是很有必要的

我觉得也很有必要。我的理解是arcface.net只是对虹软C层dll的薄薄包装，是否底层依赖于libgdiplus？
重新打开https://github.com/colin-chang/ArcFace.Net/issues/10

**Comment by colin-chang** [comment]
我也计划替换，最近公司事情比较多一直没有动手，各位可以贡献imageSharp替换代码，或者不着急的话可以等下

**Comment by kevin100702** [comment]
目前很多跨平台的方案都采用skiasharp，可以考虑使用skiasharp

**Comment by hyfree** [comment]
最佳实践：提供一个图片数据处理的抽象，（imageSharp、skiasharp）IMPL接口，提供符合要求的数据就可以了。
各位可以贡献IMPL的实现代码作为扩展。🦖

**Comment by colin-chang** [comment]
5.x版本已使用ImageSharp替换System.Drawing

**Comment by kevin100702** [comment]
您好，在升级到5.x时提示找不到 ColinChang.ArcFace.Abstraction nuget包

**Comment by colin-chang** [comment]
> 您好，在升级到5.x时提示找不到 ColinChang.ArcFace.Abstraction nuget包

已修复
