### ISSUE TITLE
有没有计划升级4.1的sdk呀

### ISSUE THREAD

**Issue by langmansh** [colin-chang/ArcFace.Net#6]
有没有计划升级4.1的sdk呀

**Comment by colin-chang** [comment]
<img width="571" alt="image" src="https://user-images.githubusercontent.com/24368158/173187598-088eeed1-d9d0-4990-afe7-f12b4ef2b9a6.png">
虹软官方最新版本为3.0 呀，没看到有 4.1 的版本，有看到的话麻烦贴个链接，谢谢
