### ISSUE TITLE
循环检测会出现提取人脸特征传入的参数错误

### ISSUE THREAD

**Issue by langmansh** [colin-chang/ArcFace.Net#7]
![QQ截图20220530161156](https://user-images.githubusercontent.com/25790561/170948143-706d21b4-e35e-4a53-8768-89b9dbf08936.jpg)

**Comment by colin-chang** [comment]
![image](https://user-images.githubusercontent.com/24368158/173189819-872642bf-d73d-4abd-9210-b58d45ce424b.png)
使用最新版本并未复现你演示的问题。请提供详细信息。
