### ISSUE TITLE
System.Drawing.Common 在.NET7 已经删除非Windows的支持

### ISSUE THREAD

**Issue by Loongle** [colin-chang/ArcFace.Net#9]
https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

**Comment by Loongle** [comment]
引发异常： System.Drawing.Common is not supported on this platform

**Comment by Loongle** [comment]
https://github.com/dotnet/designs/blob/main/accepted/2021/system-drawing-win-only/system-drawing-win-only.md

**Comment by colin-chang** [comment]
5.x版本已经使用ImageSharp替换System.Drawing
